name: myskin_flutterbytes
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  intl: ^0.18.0
  flutter_calendar_carousel: ^2.4.3
  fpdart: ^1.1.0
  extended_image: ^8.2.1
  flutter_riverpod: ^2.5.1
  permission_handler: ^11.3.1
  camera: ^0.11.0+2
  google_mlkit_barcode_scanning: ^0.12.0
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.6
  mockito: ^5.4.4
  mocktail: ^1.0.4
  flutter_local_notifications: ^17.2.3
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.3.2
  hive_flutter: ^1.1.0
  rxdart: ^0.28.0
  timezone: ^0.9.4
  carousel_slider: ^5.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
          
    - family: Orelega
      fonts: 
        - asset: assets/fonts/orelega_one/orelega_one_regular.ttf         
